<script setup lang="ts">
import { computed, defineAsyncComponent, nextTick, onMounted, reactive, ref, watch } from 'vue'
import { ArrowLeft, ArrowRight, Check, ChevronDown, CircleHelp, Clipboard, Download, Eye, Flag, LockKeyhole, RotateCcw, Settings2, Sparkles, Volume2, VolumeX, X } from 'lucide-vue-next'
import GameEmblem from './components/GameEmblem.vue'
import { capacity, cardsFor, FIBONACCI, mayEnter, NAMES, newGame, planCheck, report, restoreGame, score, TEAM_COLORS } from './game/model'
import type { GameState, Phase, WorkCard } from './game/model'
const StrategyBoard=defineAsyncComponent(()=>import('./components/StrategyBoard.vue'))
const base=import.meta.env.BASE_URL, STORAGE='istoc-sprint-odyssey-v3'
let saved:GameState|null=null
try{saved=restoreGame(JSON.parse(localStorage.getItem(STORAGE)||'null'))}catch{/* Storage is optional. */}
const state=reactive<GameState>(saved??newGame()), resumed=ref(!!saved), activeTeam=ref(0), message=ref(''), copyFeedback=ref(''), sound=ref(false)
const dialog=ref<HTMLDialogElement|null>(null), modal=ref<'rules'|'settings'|'reset'|null>(null), phaseHeading=ref<HTMLHeadingElement|null>(null)
const cap=computed(()=>capacity(state)), cards=computed(()=>cardsFor(state)), plan=computed(()=>planCheck(state)), xp=computed(()=>score(state))
const stages=['Ekibi hazırla','Tahmin et','Sprinti kur','Planı al']
const phaseCopy=[
 {eyebrow:'HAZIRLIK',title:'Önce takımını masaya oturt.',hint:'Bir ekip taşı seç. İzin kartını oynadığında masadaki kaynaklar değişsin.'},
 {eyebrow:'PLANNING POKER',title:'Aynı iş. Dört farklı bakış.',hint:'Sipariş özeti kartını birlikte tahmin edin. Herkes seçsin, sonra kartları açın.'},
 {eyebrow:'SPRİNT PLANNING',title:'Bir hedef için kartlarını oyna.',hint:'Görevleri dokunarak veya sürükleyerek masaya yerleştir. Ön koşulları birlikte düşün.'},
 {eyebrow:'BÖLÜM SONU',title:'Masadaki kararlar, gerçek bir plan.',hint:'Planı kopyala, ekibinle kullan. Sprint sonunda yalnız Done olan işleri say.'},
]
const copy=computed(()=>phaseCopy[state.phase-1]), currentName=computed(()=>NAMES[state.activePlayer])
const allVoted=computed(()=>state.votes.every(v=>v!==null)), missingNames=computed(()=>plan.value.missing.map(id=>cards.value.find(c=>c.id===id)?.title).join(', '))
const feedback=computed(()=>{
 if(!state.selected.length)return 'İlk kartını oyna. Hedef için Sepet → Özet → Sipariş → Bildirim zincirini kur.'
 if(plan.value.big)return '13 puanlık iş henüz çok belirsiz. Kart üzerindeki “Parçala” eylemini kullan.'
 if(plan.value.missing.length)return `Ön koşul eksik: ${missingNames.value}. Önce bu kartları ekle.`
 if(plan.value.over)return `${plan.value.over} SP fazla. Hedef dışındaki bir kartı çıkar veya kapsamı küçült.`
 if(!plan.value.goalMet)return 'Hedef henüz tamamlanmıyor: alıcı sipariş oluşturmalı ve durumunu görebilmeli.'
 if(!state.done.every(Boolean))return 'Hedef sığıyor. Bitmiş sayma ölçütlerini birlikte onaylayın.'
 return 'Hedefe giden işler birbirine bağlı ve kapasite içinde. Sprint planın hazır.'
})
let audioContext:AudioContext|undefined
function tap(kind='tap'){
 if(navigator.vibrate&&matchMedia('(pointer:coarse)').matches)navigator.vibrate(kind==='win'?[12,40,20]:8)
 if(!sound.value)return
 try{audioContext??=new AudioContext();void audioContext.resume();const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.connect(gain);gain.connect(audioContext.destination);osc.type='sine';osc.frequency.setValueAtTime(kind==='win'?660:kind==='card'?440:330,audioContext.currentTime);gain.gain.setValueAtTime(.035,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.12);osc.start();osc.stop(audioContext.currentTime+.13)}catch{/* Sound is optional. */}
}
function announce(text:string){message.value=text}
function go(phase:Phase){if(!mayEnter(state,phase))return;state.phase=phase;tap();nextTick(()=>{phaseHeading.value?.focus({preventScroll:true});phaseHeading.value?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'start'})})}
function adjustHours(delta:number){state.unavailable[activeTeam.value]=Math.max(0,Math.min(198,state.unavailable[activeTeam.value]+delta));tap('card');announce(`${NAMES[activeTeam.value]}: ${198-state.unavailable[activeTeam.value]} saat kullanılabilir.`)}
function completeCapacity(){state.capacityConfirmed=true;go(2)}
function castVote(n:number){if(state.revealed||state.handoff||allVoted.value)return;state.votes[state.activePlayer]=n;state.handoff=true;tap('card');announce('Kart kilitlendi. Sıradaki oyuncuya geçebilirsiniz.')}
function handOver(){if(!allVoted.value)state.activePlayer++;state.handoff=false;tap()}
function reveal(){if(!allVoted.value)return;state.revealed=true;state.handoff=false;tap('win');announce('Dört kart açıldı. Tahmin gerekçelerini konuşup ekip puanını seçin.')}
function revote(){state.votes=[null,null,null,null];state.activePlayer=0;state.handoff=false;state.revealed=false;state.agreed=null;tap()}
function agree(n:number){state.agreed=n;tap('card');announce(`Ekip tahmini ${n} SP. Bu tahmin sipariş özeti kartına uygulandı.`)}
function toggleCard(card:WorkCard){if(state.selected.includes(card.id)){state.selected=state.selected.filter(id=>id!==card.id);announce(`${card.title} desteye döndü.`)}else{state.selected.push(card.id);announce(`${card.title} sprint alanına yerleşti.`)}tap('card')}
function removeCard(id:string){const card=cards.value.find(c=>c.id===id);if(card&&state.selected.includes(id))toggleCard(card)}
function dropCard(id:string){const c=cards.value.find(x=>x.id===id);if(c&&!state.selected.includes(id))toggleCard(c)}
function dragCard(e:DragEvent,id:string){e.dataTransfer?.setData('text/plain',id);if(e.dataTransfer)e.dataTransfer.effectAllowed='copy'}
function splitCard(){state.selected=state.selected.filter(id=>id!=='integration');state.split=true;tap('win');announce('Entegrasyon işi keşif ve sandbox denemesine ayrıldı. Kalan teslimat kapsamı keşiften sonra yeniden tahminlenecek.')}
function drawEvent(){if(state.eventDrawn)return;state.eventDrawn=true;tap('card');announce('Sürpriz: bu sprintte toplam 16 saat destek gerekiyor. Plan tavanı yeniden hesaplandı.')}
function openModal(kind:'rules'|'settings'|'reset'){modal.value=kind;nextTick(()=>dialog.value?.showModal())}
function closeModal(){dialog.value?.close();modal.value=null;if(state.phase===4&&!planCheck(state).valid){state.phase=3;announce('Kapasite değişti. Planı yeniden dengele.')}}
function reset(){Object.assign(state,newGame());activeTeam.value=0;resumed.value=false;closeModal();announce('Yeni masa kuruldu.');tap()}
function setNumber(target:'focus'|'sprints'|'referenceHours',event:Event,min:number,max:number){const input=event.target as HTMLInputElement,value=Number(input.value);state[target]=Number.isFinite(value)?Math.max(min,Math.min(max,value)):min;input.value=String(state[target])}
function setHistory(i:number,e:Event){const input=e.target as HTMLInputElement;state.history[i]=Math.min(500,Math.max(0,Number(input.value)||0));input.value=String(state.history[i]);state.historySource='own'}
async function copyPlan(){try{await navigator.clipboard.writeText(report(state));copyFeedback.value='Sprint planı panoya kopyalandı.';announce(copyFeedback.value)}catch{copyFeedback.value='Panoya erişilemedi. Markdown indir düğmesini kullanabilirsin.';announce(copyFeedback.value)}tap()}
function downloadPlan(){const url=URL.createObjectURL(new Blob([report(state)],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='sprint-odyssey-plan.md';a.click();URL.revokeObjectURL(url);copyFeedback.value='Sprint planı Markdown dosyası olarak indirildi.';announce(copyFeedback.value)}
watch(state,()=>{try{localStorage.setItem(STORAGE,JSON.stringify(state))}catch{/* Continue without persistence. */}},{deep:true})
onMounted(()=>{if(resumed.value)announce('Kayıtlı oyun bu tarayıcıdan yüklendi.')})
</script>

<template>
 <div class="odyssey">
  <header class="od-header">
   <a class="od-brand" :href="`${base}efor/`"><GameEmblem kind="compass"/><span>SPRINT<br><strong>ODYSSEY</strong></span></a>
   <nav class="od-pages" aria-label="Ana sayfalar"><a :href="base">Tasks</a><a :href="`${base}efor/`" aria-current="page">Efor</a></nav>
   <div class="od-tools"><button :aria-label="sound?'Sesi kapat':'Sesi aç'" :aria-pressed="sound" @click="sound=!sound;tap()"><Volume2 v-if="sound"/><VolumeX v-else/></button><button aria-label="Oyun kuralları" @click="openModal('rules')"><CircleHelp/></button><button aria-label="Oyun ayarları" @click="openModal('settings')"><Settings2/></button></div>
  </header>
  <main id="main" class="od-main">
   <div class="campaign-bar"><span class="edition">B2B PAZARYERİ · BÖLÜM 01</span><span class="xp-token"><Sparkles :size="18"/>{{ xp }} deneyim</span></div>
   <nav class="chapter-route" aria-label="Oyunun aşamaları"><button v-for="(name,i) in stages" :key="name" :disabled="!mayEnter(state,(i+1) as Phase)" :aria-current="state.phase===i+1?'step':undefined" @click="go((i+1) as Phase)"><span class="route-stone"><Check v-if="state.phase>i+1" :size="20"/><span v-else>{{ i+1 }}</span></span><span>{{ name }}</span></button></nav>
   <div class="chapter-title"><div><p>{{ String(state.phase).padStart(2,'0') }} / {{ copy.eyebrow }}</p><h1 ref="phaseHeading" tabindex="-1">{{ copy.title }}</h1></div><button v-if="resumed" class="resume-note" @click="resumed=false">Kaldığın masadan devam <X :size="18"/></button></div>
   <p class="chapter-hint">{{ copy.hint }}</p>
   <div class="table-rim">
    <div class="table-ribbon"><span><i class="live-dot"></i>{{ state.phase===2?'TAHMİN MASASI':state.phase===3?'SPRİNT TAHTASI':state.phase===4?'TAMAMLANAN BÖLÜM':'TAKIM MASASI' }}</span><span>{{ state.phase===1?'4 OYUNCU':state.phase===2?`${state.votes.filter(v=>v!==null).length}/4 KART`:`${plan.points} / ${cap.budget} SP` }}</span></div>
    <StrategyBoard :state="state" :active-team="activeTeam" @team="activeTeam=$event;tap()" @remove="removeCard" @reveal="reveal" @drop="dropCard"/>
    <div class="table-ledger"><span><strong>{{ Math.round(cap.sprintHours) }}</strong> saat / sprint</span><span><strong>{{ cap.budget }}</strong> SP plan tavanı</span><button @click="openModal('settings')">{{ state.historySource==='example'?'Örnek geçmiş':'Kendi geçmişin' }} <ChevronDown :size="17"/></button></div>
   </div>

   <section v-if="state.phase===1" class="play-area" aria-label="Ekip hazırlığı">
    <div class="hand-heading"><div><p class="overline">ELİNDEKİ KARTLAR</p><h2>{{ NAMES[activeTeam] }} için kapasiteyi ayarla</h2></div><span class="ink-stamp">{{ 198-state.unavailable[activeTeam] }} / 198 sa</span></div>
    <div class="team-select" aria-label="Ekip üyesi"><button v-for="(name,i) in NAMES" :key="name" :aria-pressed="activeTeam===i" @click="activeTeam=i;tap()"><span class="member-dot" :style="{background:TEAM_COLORS[i]}">{{ name[0] }}</span>{{ name }}</button></div>
    <div class="capacity-hand"><button class="resource-card leave-card" @click="adjustHours(8)"><span class="card-caption">İZİN KARTI</span><GameEmblem kind="compass"/><strong>8 saat kapalı</strong><span>Kişinin aylık kapasitesinden düş</span><span class="card-action">Kartı oyna <ArrowRight :size="18"/></span></button><button class="resource-card restore-card" :disabled="state.unavailable[activeTeam]===0" @click="adjustHours(-8)"><span class="card-caption">KAYNAK KARTI</span><GameEmblem kind="spark"/><strong>8 saat geri al</strong><span>Eklediğin kapalı zamanı geri getir</span><span class="card-action">Geri getir <RotateCcw :size="18"/></span></button><div class="capacity-note"><span class="note-pin"></span><h3>Saat, elimizdeki kaynak.</h3><p>4 kişi × 198 = <strong>792 saat/ay.</strong> İzinleri çıkart; toplantı, destek ve review için odak payı ayır.</p><p>Şu an %{{ state.focus }} odakla <strong>{{ Math.round(cap.delivery) }} saat/ay</strong> teslimata ayrılıyor.</p><button class="text-action" @click="openModal('settings')">Saatleri ve geçmişi düzenle <ArrowRight :size="18"/></button></div></div>
    <p class="quiet-note">198 saat sizin brüt çalışma varsayımınız. Puan bir saat birimi değildir.</p>
   </section>

   <section v-else-if="state.phase===2" class="play-area" aria-label="Planning poker">
    <div class="story-strip"><GameEmblem kind="layers"/><div><p class="overline">TAHMİN EDİLECEK İŞ</p><h2>Sipariş özeti</h2><p>Alıcı ürünleri, toplam fiyatı ve teslimat bilgisini kontrol edebilsin. UI, API ve kabul testi kapsamda.</p></div></div>
    <div v-if="state.handoff&&!allVoted" class="handoff-panel"><LockKeyhole :size="32"/><h3>{{ currentName }} kartını kilitledi.</h3><p>Cihazı {{ NAMES[state.activePlayer+1] }}’ya verin. Kart değeri masada gizli kalır.</p><button class="wood-button" @click="handOver">{{ NAMES[state.activePlayer+1] }} hazır <ArrowRight :size="20"/></button></div>
    <div v-else-if="!allVoted" class="poker-hand-area"><div class="hand-heading"><div><p class="overline">SIRA {{ state.activePlayer+1 }} / 4</p><h2>{{ currentName }}, kartını seç.</h2></div><span class="ink-stamp"><LockKeyhole :size="18"/>Gizli oy</span></div><div class="poker-hand"><button v-for="(n,i) in FIBONACCI" :key="n" class="number-card" :style="{'--tilt':`${(i-2.5)*1.5}deg`}" :aria-label="`${currentName}: ${n} puan seç ve kilitle`" @click="castVote(n)"><span class="card-corner">{{ n }}</span><strong>{{ n }}</strong><span>{{ n===13?'BÖL':(['XS','S','M','L','XL'][i]) }}</span><span class="card-suit">✦</span></button></div><p class="quiet-note">Kapsam, karmaşıklık ve belirsizliği karşılaştır. 3 SP’lik referans: basit bir fiyat kuralı + testi.</p></div>
    <div v-else-if="!state.revealed" class="all-ready"><span class="sealed-icon"><LockKeyhole :size="28"/></span><h2>Dört kart masada. Kim ne düşündü?</h2><p>Aynı cihazla sıra usulü oynuyorsunuz. Bütün oylar birlikte açılacak.</p><button class="wood-button" @click="reveal"><Eye :size="20"/>Kartları birlikte aç</button></div>
    <div v-else class="consensus-area"><div class="vote-receipt"><span v-for="(name,i) in NAMES" :key="name"><span class="member-dot" :style="{background:TEAM_COLORS[i]}">{{ name[0] }}</span>{{ name }} <strong>{{ state.votes[i] }} SP</strong></span></div><div class="hand-heading"><div><p class="overline">ORTAK KARAR</p><h2>Gerekçeleri konuşun, bir puanda anlaşın.</h2></div><button class="text-action" @click="revote"><RotateCcw :size="18"/>Tekrar oyla</button></div><p>En düşük ve en yüksek oyu veren başlayabilir. Ortalama otomatik karar vermez.</p><div class="agreement-choices"><button v-for="n in FIBONACCI" :key="n" :aria-pressed="state.agreed===n" @click="agree(n)">{{ n }} SP <Check v-if="state.agreed===n" :size="18"/></button></div><p v-if="state.agreed===13" class="game-alert">13 SP: kapsamı küçültüp yeniden oylayın. Bu büyüklükteki özeti sprint içine alamayacaksınız.</p><p v-else-if="state.agreed" class="game-success">Sipariş özeti {{ state.agreed }} SP olarak desteye eklendi.</p></div>
   </section>

   <section v-else-if="state.phase===3" class="play-area" aria-label="Sprint kart destesi">
    <div class="goal-banner"><Flag :size="24"/><div><p class="overline">BU SPRİNTİN HEDEFİ</p><strong>{{ state.goal }}</strong></div><button class="text-action" @click="openModal('settings')">Düzenle</button></div>
    <div class="hand-heading"><div><p class="overline">GÖREV DESTESİ</p><h2>Hedefe hizmet eden kartları seç.</h2></div><span class="ink-stamp" :class="{'danger-stamp':plan.over}">{{ plan.points }} / {{ cap.budget }} SP</span></div>
    <div class="quest-hand"><article v-for="card in cards" :key="card.id" class="quest-piece" :data-tone="card.color" :class="{'is-played':state.selected.includes(card.id)}"><button class="quest-face" draggable="true" :aria-label="`${card.title}, ${card.points} SP, ${state.selected.includes(card.id)?'sprintten çıkar':'sprinte ekle'}`" :aria-pressed="state.selected.includes(card.id)" @dragstart="dragCard($event,card.id)" @click="toggleCard(card)"><span class="quest-top"><span>{{ card.goal?'HEDEF GÖREVİ':'YAN GÖREV' }}</span><strong>{{ card.points }}<small>SP</small></strong></span><GameEmblem :kind="card.suit"/><h3>{{ card.title }}</h3><p>{{ card.description }}</p><span class="dependency-note">{{ card.depends.length?`Önce: ${card.depends.map(id=>cards.find(c=>c.id===id)?.short).join(' + ')}`:'Bağımsız başlayabilir' }}</span><span class="card-action"><Check v-if="state.selected.includes(card.id)" :size="18"/><span>{{ state.selected.includes(card.id)?'MASADA · GERİ AL':'SPRİNTE EKLE' }}</span><ArrowRight v-if="!state.selected.includes(card.id)" :size="18"/></span></button><button v-if="card.id==='integration'" class="split-action" @click="splitCard">13 SP · Parçala <Sparkles :size="18"/></button></article></div>
    <div class="planning-feedback" :class="{'needs-attention':plan.over||plan.missing.length||plan.big}"><span class="feedback-symbol">{{ plan.valid?'✓':'i' }}</span><p>{{ feedback }}</p></div>
    <div class="sprint-bottom"><div class="event-card" :class="{'event-open':state.eventDrawn}"><div class="event-seal"><GameEmblem kind="spark"/></div><div><p class="overline">SÜRPRİZ KARTI · İSTEĞE BAĞLI</p><h3>{{ state.eventDrawn?'Destek çağrısı!':'Planın değişirse?' }}</h3><p>{{ state.eventDrawn?'Bu sprintte toplam 16 saat destek gerekiyor. Kaynak azaldı; plan tavanı güncellendi.':'Bir olay kartı aç ve değişen kapasiteye göre planını yeniden düzenle.' }}</p></div><button v-if="!state.eventDrawn" class="wood-button" @click="drawEvent">Kartı aç</button><strong v-else>−16 saat</strong></div><fieldset class="done-list"><legend>Bir işi ne zaman bitmiş sayarız?</legend><label v-for="(text,i) in ['Testler geçti, kod incelendi.','Kabul kriterleri doğrulandı.','Artırım kullanılabilir; yarım iş Done değil.']" :key="text"><input v-model="state.done[i]" type="checkbox"/><span>{{ text }}</span></label></fieldset></div>
   </section>

   <section v-else class="play-area result-area" aria-label="Sprint planı raporu">
    <div class="result-medallion"><span>MASA TAMAMLANDI</span><strong>{{ xp }}</strong><span>DENEYİM PUANI</span></div>
    <div class="plan-paper"><span class="paper-stamp">SPRİNT PLANI</span><h2>{{ state.goal }}</h2><p>{{ NAMES.join(' · ') }}</p><div class="report-metrics"><span><strong>{{ Math.round(cap.sprintHours) }} saat</strong>Bu sprint odak kapasitesi</span><span><strong>{{ plan.points }} / {{ cap.budget }} SP</strong>Seçilen / plan tavanı</span><span><strong>{{ cap.velocity.toFixed(1) }} SP</strong>Geçmiş Done ortalaması</span></div><ul class="plan-items"><li v-for="card in plan.cards" :key="card.id"><Check :size="18"/><span>{{ card.title }}</span><strong>{{ card.points }} SP</strong></li></ul><p class="report-assumption">{{ state.historySource==='example'?'Örnek veri ile eğitim planı. Gerçek ekip geçmişi henüz girilmedi.':'Girdiğiniz geçmişle hesaplanan tahmin.' }} Geçmiş: {{ state.history.join(' / ') }} SP. %15 tampon yalnız bir kez uygulandı.</p><div class="report-actions"><button class="wood-button" @click="copyPlan"><Clipboard :size="20"/>Planı kopyala</button><button class="outline-button" @click="downloadPlan"><Download :size="20"/>Markdown indir</button></div><p v-if="copyFeedback" class="game-success export-feedback">{{ copyFeedback }}</p></div>
    <div class="retro-note"><GameEmblem kind="compass"/><div><h3>Bir sonraki turda gerçeği masaya koy.</h3><p>Sprint sonunda yalnız bitmiş işleri say. Sonucu geçmişe ekleyip sonraki planı güncelle. XP öğrenme içindir; kişisel performans ölçüsü değildir.</p><button class="text-action" @click="openModal('reset')">Yeni masa kur <ArrowRight :size="18"/></button></div></div>
   </section>
   <footer class="game-credits"><span>Tek cihazda, sıra usulü · Oyun bu tarayıcıda saklanır</span><button @click="openModal('rules')">Oyun kılavuzu ve kaynaklar <CircleHelp :size="18"/></button></footer>
  </main>
  <div class="turn-dock"><button class="dock-back" aria-label="Önceki aşamaya dön" :disabled="state.phase===1" @click="go((state.phase-1) as Phase)"><ArrowLeft :size="22"/><span>Geri</span></button><p>{{ state.phase===1?'Kaynaklar hazırsa ilk tur başlasın.':state.phase===2?(state.agreed?'Ortak tahmin seçildi.':'Oy verin, açın ve ortak puanı seçin.'):state.phase===3?feedback:'Planın kopyalanmaya hazır.' }}</p><button v-if="state.phase===1" class="wood-button" @click="completeCapacity">Ekibi masaya al <ArrowRight :size="20"/></button><button v-else-if="state.phase===2" class="wood-button" :disabled="state.agreed===null||state.agreed===13" @click="go(3)">Sprinti kur <ArrowRight :size="20"/></button><button v-else-if="state.phase===3" class="wood-button" :disabled="!plan.valid" @click="go(4);tap('win')">Planı tamamla <ArrowRight :size="20"/></button><button v-else class="wood-button" @click="copyPlan"><Clipboard :size="20"/>Planı kopyala</button></div>
  <div class="game-announcement" role="status" aria-live="polite">{{ message }}</div>
  <dialog ref="dialog" class="od-dialog" @close="modal=null" @click="($event.target===dialog)&&closeModal()"><div v-if="modal" class="dialog-paper"><header><h2>{{ modal==='rules'?'Masaya hoş geldin.':modal==='settings'?'Oyunun varsayımları':'Yeni bir masa?' }}</h2><button class="close-button" aria-label="Pencereyi kapat" @click="closeModal"><X/></button></header>
   <template v-if="modal==='rules'"><p>Bir B2B ekibinin bir sprintini planlıyorsun. Amaç, tek hedefe hizmet eden bitirilebilir bir iş paketi kurmak.</p><ol class="rules-list"><li><strong>1. Ekibi hazırla.</strong> 198 saat/kişi aylık brüt varsayımından izinleri çıkar. Odak payı, toplantı ve rutin destek payını ayırır.</li><li><strong>2. Kartları kapalı seç.</strong> Aynı cihazı sırayla kullanın. Dört oy açılınca gerekçeleri konuşun; son puanı ekip seçer.</li><li><strong>3. Hedefe göre oyna.</strong> Kartlara dokun veya masaüstünde sürükle. Ön koşulları tamamla. 13 SP’lik belirsiz işleri parçala.</li><li><strong>4. Planı al.</strong> Kabul ve Done ölçütlerini onayla. Planı kopyala; sprint sonunda gerçekleşeni ölç.</li></ol><h3>Saat ve puan neden ayrı?</h3><p>Saat, uygunluk bilgisidir. Story point göreli büyüklüktür. Fibonacci, t-shirt boyutu ve %15 tampon burada seçilen yardımcı yöntemlerdir; Scrum’ın zorunlu kuralları değildir.</p><p>Plan tavanı = geçmiş Done SP ortalaması × (bu sprint odak saati / geçmiş sprint referans saati) × 0,85. Bu kapasite oranı bir planlama varsayımıdır; sabit “1 SP = X saat” dönüşümü kullanılmaz. Aynı ekip ve benzer sprint süreleriyle kullanın.</p><p>Başlangıçta 18, 22, 20 SP ve 257,4 saat referansı <strong>örnek veridir</strong>. Kendi değerlerini ayarlardan gir. Sıfır puanla biten sprintler de ortalamaya dahildir.</p><h3>Oyun malzemeleri</h3><p>Tahta ve taşlar özel vektör çizimleridir. Etkileşimler <a href="https://pixijs.com/" target="_blank" rel="noreferrer">PixiJS</a> ve <a href="https://github.com/pixijs/ui" target="_blank" rel="noreferrer">Pixi UI</a> ile çalışır. Kart açma yüzeyi: <a href="https://kenney.nl/assets/ui-pack" target="_blank" rel="noreferrer">Kenney UI Pack · CC0</a>.</p><p><a href="https://scrumguides.org/scrum-guide.html" target="_blank" rel="noreferrer">Scrum Guide</a> · <a :href="`${base}game/CREDITS.md`" target="_blank">Görsel lisansları</a></p><button class="wood-button" @click="closeModal">Masaya dön <ArrowRight :size="20"/></button></template>
   <template v-else-if="modal==='settings'"><p>Değişiklikler canlı hesaplanır. Kapalı saatlere izin/uygunsuzluğu yaz; odak payında aynı kaybı ikinci kez sayma.</p><div class="settings-grid"><label v-for="(name,i) in NAMES" :key="name">{{ name }} · aylık kapalı saat<input :value="state.unavailable[i]" type="number" min="0" max="198" step="1" @change="state.unavailable[i]=Math.max(0,Math.min(198,Number(($event.target as HTMLInputElement).value)||0));($event.target as HTMLInputElement).value=String(state.unavailable[i])"/></label><label>Odak payı (%)<input :value="state.focus" type="number" min="10" max="100" @change="setNumber('focus',$event,10,100)"/></label><label>Ayda sprint sayısı<input :value="state.sprints" type="number" min="1" max="4" step="1" @change="setNumber('sprints',$event,1,4);state.sprints=Math.round(state.sprints)"/></label></div><fieldset class="history-settings"><legend>Tamamlanan son 3 sprint (Done SP)</legend><p>{{ state.historySource==='example'?'Şu an örnek değerler var. Gerçek ölçümü girince kaynak etiketi değişir.':'Kendi girdiğiniz geçmiş kullanılıyor.' }}</p><div class="settings-grid"><label v-for="(_,i) in state.history" :key="i">Sprint {{ i+1 }}<input :value="state.history[i]" type="number" min="0" max="500" @change="setHistory(i,$event)"/></label></div><label>Bu geçmişin ortalama ekip odak saati / sprint<input :value="state.referenceHours" type="number" min="1" max="2000" step=".1" @change="setNumber('referenceHours',$event,1,2000);state.historySource='own'"/></label></fieldset><label>Sprint hedefinin ifadesi<textarea v-model="state.goal" maxlength="400" rows="3"/></label><p class="quiet-note">Bu bölüm sipariş oluşturma ve takip hedefini öğretir. İfadeyi düzenleyebilirsin; başarı için Sepet, Özet, Sipariş ve Bildirim kartları gerekir.</p><button class="wood-button" @click="closeModal">Ayarları uygula <Check :size="20"/></button><button class="text-action" @click="modal='reset'">Oyunu baştan başlat <RotateCcw :size="18"/></button></template>
   <template v-else><p>Bu tarayıcıdaki oyun ilerlemesi sıfırlanacak. İndirdiğin veya kopyaladığın planlar sende kalır.</p><div class="report-actions"><button class="outline-button" @click="closeModal">Masada kal</button><button class="wood-button" @click="reset">Yeni masa kur</button></div></template>
  </div></dialog>
 </div>
</template>
